logging:
  level:
    org.dclou.example.demogpb: TRACE
    org.springframework.security: DEBUG

spring:
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    addresses: rabbit-mon
    username: admin
    password: admin
    virtual-host: rabbit-mon
  data:
    rest:
      basePath: /api
  cloud:
    inetutils:
      preferred-networks:
        - 10.0
      ignored-interfaces:
        - eth2
        - eth2@*

encrypt:
  failOnError: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: ${spring.application.name}
    metadataMap.instanceId: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30

management:
  security:
    enabled: false
  trace:
    include: request_headers,response_headers,cookies,authorization_header,errors,path_info,path_translated,context_path,user_principal,parameters,query_string,auth_type,remote_address,session_id,remote_user

server:
  port: 8083
  session:
    cookie:
      name: JSESSIONIDCATALOGSRV

ribbon:
  eureka:
    enabled: true

security:
  sessions: stateless
  user:
    password: password
