sudo: required

branches:
  only:
  - master
  - release

services:
  - docker

addons:
  ssh_known_hosts: 178.159.32.129

script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B package -DskipTests

before_deploy:
  - openssl aes-256-cbc -K $encrypted_61f7c845f286_key -iv $encrypted_61f7c845f286_iv -in deploy/deploy_rsa.enc -out deploy/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy/deploy_rsa
  - ssh-add deploy/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: deploy/deploy.sh 178.159.32.129
  on:
    branch: release
